### ISSUE TITLE
/model/predict doesn't handle invalid input

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Image-Caption-Generator#3]
If an invalid input (such as a text file or certain images) is provided as payload the server returns status code 500 (Internal Server Error). The log output contains stack trace information, indicating that the input is not valid. 

To recreate:
* Invoke the `/model/predict` endpoint and provide an invalid "image" as input

Actual result:
* Server returns HTTP status code `500 (Internal Server Error)`

Expected result:
* Server returns HTTP status code `400 (Bad Request)`

**Comment by bdwyer2** [comment]
Looks like this was fixed by #9. @ptitzler can we close this?

**Comment by ptitzler** [comment]
:+1: Verified.
