### ISSUE TITLE
Deploy on Amazon SageMaker

### ISSUE THREAD

**Issue by oelesinsc24** [IBM/MAX-Image-Caption-Generator#44]
Do you have any recommendations on deploying this to Amazon SageMaker?

Likewise, can I retrain on my custom dataset?

Thanks in advance

**Comment by MLnick** [comment]
Hi there, thanks for your interest in the Model Asset Exchange! 

I'm afraid we cannot assist with SageMaker, being unfamiliar with the details of how that service works. I'd suggest looking into their documentation to see if they support arbitrary Docker container deployments.

For now, we don't support training this model on a custom dataset, please see #46 for details of the underlying training code repo that you can use for that.
