### ISSUE TITLE
Training on custom dataset ?

### ISSUE THREAD

**Issue by pidugusundeep** [IBM/MAX-Image-Caption-Generator#46]
Hey, I am curious if I could use my own dataset for training instead of the COCO dataset which is already being used.

**Comment by djalova** [comment]
Hello, we currently do not support retraining for this MAX model yet, but if you want to try it out on your own you can find the source code here.
https://github.com/tensorflow/models/tree/master/research/im2txt

**Comment by pidugusundeep** [comment]
Thanks will check that out @djalova
