### ISSUE TITLE
fix or disable downstream build

### ISSUE THREAD

**Issue by bdwyer2** [IBM/MAX-Image-Caption-Generator#50]
The downstream build (max-image-caption-Generator
-web-app) has been failing for a while. We should either fix this or disable this.

**Comment by bdwyer2** [comment]
cc @ajbozarth

**Comment by ajbozarth** [comment]
oh, #45 never got merged, we discussed this and disabled it in that PR, feel free to add/merge that chunk of code if that PR wont be merged soon

**Comment by bdwyer2** [comment]
Temporarily disabled via #61
