### ISSUE TITLE
Not working from docker hub

### ISSUE THREAD

**Issue by bdwyer2** [IBM/MAX-Image-Caption-Generator#6]
The image doesn't work when pulled from Docker Hub. Tried on 2 separate Ubuntu machine and got the same result

```brendan@oxygen ~ $ docker run -it --rm -p 5000:5000 codait/max-image-caption-generator-web-app
Unable to find image 'codait/max-image-caption-generator-web-app:latest' locally
latest: Pulling from codait/max-image-caption-generator-web-app
ff3a5c916c92: Already exists 
44014a6ad6bc: Pull complete 
2f8f143a8987: Pull complete 
02b100ec4a6d: Pull complete 
c74d77b2e916: Pull complete 
d5ebd2bdbe85: Pull complete 
9bd06c12144a: Pull complete 
Digest: sha256:aefaf3a41e1f9b51c4fbf39791bdd8303ef6084d7e8e4e0db0090b57a46a8243
Status: Downloaded newer image for codait/max-image-caption-generator-web-app:latest
INFO: Connecting to ML endpoint at http://localhost:5000/model/predict
ERROR: Cannot connect to the Image Caption Generator REST endpoint at http://localhost:5000
```

**Comment by lresende** [comment]
If this is an issue, should it actually be a webapp issue? and not attached to the model?

Also, the steps below seem to work, basically running the webapp does not automatically load/run the dependency images, you will need to create a docker composer file linking the two.
```
docker run -it -p 5000:5000 --name max-im2txt codait/max-image-caption-generator
docker run --net='container:max-im2txt' -it codait/max-image-caption-generator-web-app
```

But with --net being used, how can I access the webapp ui then? 
@ajbozarth ^^^

**Comment by bdwyer2** [comment]
I didn't realize that there are separate repositories. I will open an issue there.

**Comment by ajbozarth** [comment]
@bdwyer2 @lresende The instructions to run the web app using Docker are included at the botton of the Steps section in the web app repo as Luciano referenced. As for using docker hub for the web app, those instructions are being adding in the open PR I'm currently working on: IBM/MAX-Image-Caption-Generator-Web-App#33
