### ISSUE TITLE
Unable to resolve host address

### ISSUE THREAD

**Issue by danaibrilli** [IBM/MAX-Image-Caption-Generator#77]
Hello! I was trying to deploy the model locally, so after cloning the github repository, I had to build the docker file with the command : sudo docker build -t max-image-caption-generator .
However, at Step 4/10 I get the error:
![unable_host](https://user-images.githubusercontent.com/36965213/149668803-e2561cbb-dcd3-486e-92b5-c4b35067c756.png)

**Comment by lutharsanen** [comment]
i had the same issue as well

**Comment by kmh4321** [comment]
This is now fixed in #78
